### ISSUE TITLE
pip install fails in GitHub CI with metadata-generation-failed

### ISSUE THREAD

**Issue by Jnesselr** [miurahr/pyppmd#101]
**Describe the bug**
I'm still not 100% sure if it's a bug in this repo or a standards change, but I'm getting a failure to install this library in our CI (private, log below) that I can't reproduce locally. I don't 100% understand pyproject.toml stuff to be able to debug this myself, but one thing I found is this part of the log:
```
      configuration error: `project` must contain ['version'] properties
      DESCRIPTION:
          version should be statically defined in the ``version`` field
```

**Related issue**
I also found #95 as a PR in this repo and pypa/setuptools#3199 as potential related issues given the timing of when this started failing for us.

Unfortunately, I'm not 100% sure what the actual fix is here or how related those related issues are. Please let me know if I can help you get more info.

**Environment (please complete the following information):**
 - OS: Mac OS X 11.6.5 (Github CI)
 - Python 3.10.3
 - project version: 0.18.1

```
Run jurplel/install-qt-action@v3
  with:
    version: 5.15.2
    py7zrversion: >=0.18.0
    target: desktop
    install-deps: true
    cached: false
    setup-python: true
    set-env: true
    tools-only: false
    aqtversion: ==2.0.0
Successfully setup CPython (3.10.3)
brew install p7zip
Warning: p7zip 17.04 is already installed and up-to-date.
To reinstall 17.04, run:
  brew reinstall p7zip
python3 -m pip install setuptools wheel
Requirement already satisfied: setuptools in /Users/runner/hostedtoolcache/Python/3.10.3/x64/lib/python3.10/site-packages (58.1.0)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
python3 -m pip install py7zr>=0.18.0
Collecting py7zr>=0.18.0
  Downloading py7zr-0.18.3-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 KB 6.7 MB/s eta 0:00:00
Collecting pyppmd<0.19.0,>=0.18.1
  Downloading pyppmd-0.18.1.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.8 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      configuration error: `project` must contain ['version'] properties
      DESCRIPTION:
          version should be statically defined in the ``version`` field
      
      GIVEN VALUE:
          {
              "name": "pyppmd",
              "requires-python": ">=3.6",
                      "sphinx>=2.3",
                      "sphinx_rtd_theme"
                  ],
                  "fuzzer": [
                      "atheris",
                      "hypothesis"
                  ]
              },
              "urls": {
                  "Source": "https://github.com/miurahr/pyppmd"
              }
          }
      
      OFFENDING RULE: 'required'
      
      DEFINITION:
          {
              "required": [
                  "version"
              ]
          }
      Traceback (most recent call last):
        File "/Users/runner/hostedtoolcache/Python/3.10.3/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/runner/hostedtoolcache/Python/3.10.3/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/runner/hostedtoolcache/Python/3.10.3/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 84, in <module>
          setup(
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 854, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-bh_hq6sv/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
          raise error from None
      ValueError: invalid pyproject.toml config: `project`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: The process 'python3' failed with exit code 1
```

**Comment by Jnesselr** [comment]
Forgot to mention that I did find https://github.com/miurahr/pyppmd/issues/94#issuecomment-1084580179 but I'm not sure if that's been released yet.

**Comment by miurahr** [comment]
I wandering why it try to compile pyppmd package from source, not using a wheel package.
I found release don't have python 3.10 universal binary package.

https://pypi.org/project/pyppmd/#files

**Comment by miurahr** [comment]
A fix is pushed to master.

Packages of snapshot  are published in test.pypi.org
https://test.pypi.org/project/pyppmd/0.18.2.dev9/#files

It looks good so I'd like to release v0.18.2.

**Comment by miurahr** [comment]
v0.18.2 will out soon.

**Comment by Jnesselr** [comment]
Looks good on our side, thank you!
